import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const LIGHT_SELECTOR = ':root,\n[data-theme="light"]';
const DARK_SELECTOR = '[data-theme="dark"]';

const REM_SCALES = [
  "radius",
  "size-unit",
  "typography-font-size",
  "typography-line-height",
];
const PX_TOKENS = new Set(["radius-pill"]);
const ROOT_FONT_SIZE = 16;

export function compileTokenCss(root) {
  const globalTokens = collectTokens(loadTokenGroup(root, "global"), [], []);
  const themeTokens = collectTokens(loadTokenGroup(root, "theme"), [], []);
  const globalLines = globalTokens.map(
    ({ name, node }) =>
      `  --${name}: ${formatValue(node.$value, node.$type, name)};`,
  );
  const lightLines = [];
  const darkLines = [];

  for (const { name, node } of themeTokens) {
    const modes = node.$extensions?.mode ?? {};

    lightLines.push(
      `  --${name}: ${formatValue(modes.light ?? node.$value, node.$type, name)};`,
    );
    darkLines.push(
      `  --${name}: ${formatValue(modes.dark ?? modes.light ?? node.$value, node.$type, name)};`,
    );
  }

  return {
    css: `/* GENERATED by scripts/build-css.mjs — do not edit by hand.
   Source of truth: tokens/global and tokens/theme.
   Regenerate:      npm run build */

:root {
${globalLines.join("\n")}
}

${LIGHT_SELECTOR} {
${lightLines.join("\n")}
}

${DARK_SELECTOR} {
${darkLines.join("\n")}
}
`,
    globalCount: globalTokens.length,
    themeCount: themeTokens.length,
  };
}

function loadTokenGroup(root, group) {
  const merged = {};

  for (const file of walkJsonFiles(join(root, group)).sort()) {
    deepMerge(merged, JSON.parse(readFileSync(file, "utf8")));
  }

  const tree = merged[group];

  if (!tree || typeof tree !== "object" || Array.isArray(tree)) {
    throw new Error(`${group} tokens must be nested under a "${group}" object.`);
  }

  return tree;
}

function walkJsonFiles(dir) {
  const out = [];

  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);

    if (statSync(full).isDirectory()) {
      out.push(...walkJsonFiles(full));
    } else if (entry.endsWith(".json")) {
      out.push(full);
    }
  }

  return out;
}

function deepMerge(dst, src) {
  for (const [key, value] of Object.entries(src)) {
    if (isPlainObject(value) && isPlainObject(dst[key])) {
      deepMerge(dst[key], value);
    } else {
      dst[key] = value;
    }
  }

  return dst;
}

function collectTokens(tree, path, acc) {
  if (isPlainObject(tree) && "$value" in tree) {
    assertTokenNode(tree, path);
    acc.push({ name: path.join("-"), node: tree });
    return acc;
  }

  if (isPlainObject(tree)) {
    for (const [key, value] of Object.entries(tree)) {
      if (!key.startsWith("$")) {
        collectTokens(value, [...path, key], acc);
      }
    }
  }

  return acc;
}

function assertTokenNode(node, path) {
  const label = path.join(".") || "(root)";

  if (typeof node.$type !== "string" || node.$type.trim() === "") {
    throw new Error(`${label} must declare a $type.`);
  }
}

function formatValue(value, type, name) {
  if (isAlias(value)) {
    return aliasVar(value);
  }

  if (type === "cubicBezier" && Array.isArray(value)) {
    return `cubic-bezier(${value.join(", ")})`;
  }

  if (type === "shadow") {
    const layers = Array.isArray(value) ? value : [value];

    return layers.map(shadowLayer).join(", ");
  }

  if (type === "dimension" && scalesWithText(name)) {
    return toRem(String(value));
  }

  return String(value);
}

function isAlias(value) {
  return typeof value === "string" && /^\{.+\}$/.test(value);
}

function aliasVar(value) {
  return `var(--${value.slice(1, -1).split(".").slice(1).join("-")})`;
}

function shadowLayer(shadow) {
  return `${shadow.offsetX} ${shadow.offsetY} ${shadow.blur}${
    shadow.spread && shadow.spread !== "0px" ? ` ${shadow.spread}` : ""
  } ${shadow.color}`;
}

function scalesWithText(name) {
  return (
    !PX_TOKENS.has(name) &&
    REM_SCALES.some((scale) => name === scale || name.startsWith(`${scale}-`))
  );
}

function toRem(value) {
  if (!/^-?[\d.]+px$/.test(value)) {
    return value;
  }

  const px = Number.parseFloat(value);

  return px === 0 ? "0" : `${px / ROOT_FONT_SIZE}rem`;
}

function isPlainObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}
